name: DevSecOps Pipeline

on: [push, pull_request]

permissions:
  contents: read
  issues: write
  checks: write
  pull-requests: write

jobs:

  # ÉTAPE 1 : ANALYSE DU CODE (SAST & SECRETS)
  security-code-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Gitleaks - Secret Scanning
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Semgrep - SAST
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/python

  # ÉTAPE 2 : BUILD & CONTAINER SCAN
  build-and-scan-image:
    needs: security-code-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t myapp:${{ github.sha }} ./services/catalog

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'myapp:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  # ÉTAPE 3 : DAST (Test dynamique)
  dast-scan:
    needs: build-and-scan-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build & Run App
        run: |
          docker build -t myapp:target ./services/catalog
          docker run -d -p 5000:5000 --name target-app myapp:target
          sleep 5

      - name: Fix permissions for ZAP
        run: chmod -R 777 .

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:5000'
          fail_action: true

  # ÉTAPE 4 : RUNTIME MONITORING GATE (Partie F du TP2)
  runtime_gate:
    needs: dast-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Launch Staging for Monitoring
        run: |
          docker compose -f compose.staging.yml down -v
          docker compose -f compose.staging.yml up -d --build
          sleep 5

      - name: Run Runtime Security Gate
        run: |
          BASE_URL=http://localhost:5002 SERVICE=catalog MAX_5XX=5 bash monitoring/log_gate.sh
        
      - name: Archive Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: runtime-monitoring-reports
          path: reports/
